apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prom-test
  name: prom-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-test
  template:
    metadata:
      labels:
        app: prom-test
    spec:
      containers:
      - image: mingbo/prom-test
        imagePullPolicy: Always
        name: prom-test
        resources: 
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"      
        ports:
          - containerPort: 5000
            name: web
