apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-test
  name: otel-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-test
  template:
    metadata:
      labels:
        app: otel-test
      annotations:
        instrumentation.opentelemetry.io/inject-python: "monitoring/python"
    spec:
      containers:
      - image: mingbo/otel-manual
        imagePullPolicy: Always
        name: otel-test
        resources: 
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"      
        ports:
          - containerPort: 5000
            name: web
