apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-demo-{{ .Values.service_name }}
  name: service-demo-{{ .Values.service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-demo-{{ .Values.service_name }}
  template:
    metadata:
      labels:
        app: service-demo-{{ .Values.service_name }}
      annotations:
        instrumentation.opentelemetry.io/inject-python: "monitoring/python"
    spec:
      containers:
      - image: mingbo/service_demo
        imagePullPolicy: Always
        name: service-demo-{{ .Values.service_name }}
        resources: 
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"      
        ports:
          - containerPort: 5000
            name: web
        env:
          - name: SVC_NAME
            value: "{{ .Values.service_name }}"

--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-demo-{{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: service-demo-{{ .Values.service_name }}
